### ISSUE TITLE
Add dashes when converting PascalCase to kebab-case

### ISSUE THREAD

**Issue by focusaurus** [raiseandfall/slugify-files#3]
I'd like to request mixed-case file names like "ThroughTheLookingGlass.txt" be renamed with dashes between capitalized words: "through-the-looking-glass.txt".

**Comment by raiseandfall** [comment]
@focusaurus good idea. I'm a bit too busy to take care of that right now, but I will when I have a sec. In the meantime if you want to open a PR, you're more than welcome ;)
